/**
 * Typed wrappers for chat backend routes with retry-with-key on network failure.
 *
 * Sprint 2 additions (Wave 3 wire-shape):
 *   - `attachments` — up to 4 `{type:'image', url}` entries; the URL is the
 *     signed GET URL returned by the upload helper (`lib/uploads/photo-upload.ts`).
 *   - `amend.targetDecisionId` — present whenever the chat surface was
 *     opened with `?amendDecisionId=<id>`. Routes the AI tool-loop through
 *     a future `propose_amend` super-cede path; for Sprint 2 the field is
 *     accepted by zod and threaded through to the chat-message audit row.
 *
 * Idempotency: every send carries an Idempotency-Key header generated by
 * `generateIdempotencyKey()`. On retry, the SAME key is sent so the backend's
 * `ChatRequestLog` short-circuits to the original response (Sprint 1
 * Cluster F pattern). No new keying is needed for attachments or amend —
 * the chat envelope is the idempotency unit.
 *
 * @derives(master-plan §G)
 * @derives(supervisor-drawer-and-decisions-redesign.md §C — chat photo attach)
 * @derives(supervisor-drawer-and-decisions-redesign.md §D.3 — amend pathway)
 */

import { apiFetch, ApiError } from './api';

/**
 * Single photo attachment, ready to send on a `POST /chat/messages` body.
 *
 * The URL is the signed-GET URL returned by `uploadPhotoAttachment()`. The
 * backend persists `attachments[]` on the user-row's `toolCalls.attachments`
 * JSON (per Wave 3 done-memo §1 modified-files) and surfaces a hint note to
 * the AI tool-loop before classification.
 */
export type ChatAttachment = {
  readonly type: 'image';
  readonly url: string;
};

/**
 * Amend metadata. When present, the chat send body includes
 * `amend: { targetDecisionId }`. See `ChatAmendInput` in shared-schema for
 * the contract.
 */
export type ChatAmendMeta = {
  readonly targetDecisionId: string;
};

export type DecisionCardData = {
  toolName?: string;
  toolCallId?: string;
  /** SupervisorDecision.id minted by the backend tool-loop. */
  decisionId?: string;
  title?: string;
  description?: string;
  fields?: Record<string, unknown>;
  severity?: 'OK' | 'CONFIRM' | 'WARN' | 'BLOCKED';
  presets?: { chips?: Array<{ label: string; value: string }> };
  /**
   * Wave 3 `propose_clarify` flag. When true, `fields.options: string[]`
   * holds the tappable clarifying chips (max 4). Mobile renders the chips
   * inline below the assistant bubble; tapping a chip injects the chosen
   * option as the next user message.
   */
  clarify?: boolean;
  /**
   * Wave 3 `propose_log_complaint` extension. When the tool fires from a
   * chat turn, this is set to `'CHAT'`. Used by mobile to render the
   * inline confirmation bubble (vs. the standard apply-or-dismiss
   * DecisionCard variant).
   */
  origin?: 'CHAT' | 'DIRECT';
} | null;

export type ChatMessageResponse = {
  chatMessageId: string;
  assistantText: string;
  /** Singular card — present when the AI emits 0 or 1 propose_* tool calls. */
  decisionCard: DecisionCardData;
  /**
   * Plural batch — present when the AI emits 2+ propose_* tool calls in a
   * single turn (compound utterance). When set, decisionCard is null. Wave 4a-PRO Task 10.
   */
  decisionCards?: NonNullable<DecisionCardData>[] | null;
  /**
   * Cluster A fix (Sprint 2 deep-review 2026-05-18). Server-set flag that
   * tells the client whether THIS turn actually amended an existing
   * decision. True iff the request carried a valid `amend.targetDecisionId`
   * AND the backend validated + persisted it. Mobile gates the
   * "amend complete" celebration on this — not on whether any tool fired.
   */
  didAmend?: boolean;
};

export type SendChatMessageInput = {
  text: string;
  voiceConfidence?: 'HIGH' | 'MEDIUM' | 'LOW';
  idempotencyKey: string;
  /**
   * Optional photo attachments. Each entry must already be uploaded — the
   * URL is sent as-is to the backend, which records it on the chat-message
   * audit row and includes it in the AI context hint.
   */
  attachments?: ReadonlyArray<ChatAttachment>;
  /**
   * Amend metadata. When the chat surface is in amend mode (opened with
   * `?amendDecisionId=<id>`), this is set on every send until the AI
   * returns a successful tool result that completes the amend.
   */
  amend?: ChatAmendMeta;
  /** For testing: shorten retry backoff. Default 2000. */
  retryDelayMs?: number;
};

/**
 * Send a chat message with retry-with-same-key on network failure.
 * 3 retries with exponential backoff. Same Idempotency-Key on every retry.
 */
export async function sendChatMessage(input: SendChatMessageInput): Promise<ChatMessageResponse> {
  const baseDelay = input.retryDelayMs ?? 2000;
  const maxRetries = 3;

  // Build body once so retries are byte-identical.
  const body: {
    text: string;
    voiceConfidence?: 'HIGH' | 'MEDIUM' | 'LOW';
    attachments?: ChatAttachment[];
    amend?: ChatAmendMeta;
  } = { text: input.text };
  if (input.voiceConfidence) body.voiceConfidence = input.voiceConfidence;
  if (input.attachments && input.attachments.length > 0) {
    body.attachments = input.attachments.map((a) => ({ type: a.type, url: a.url }));
  }
  if (input.amend) body.amend = { targetDecisionId: input.amend.targetDecisionId };

  let lastError: unknown;
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      return await apiFetch<ChatMessageResponse>('/chat/messages', {
        method: 'POST',
        body,
        headers: { 'Idempotency-Key': input.idempotencyKey },
      });
    } catch (err) {
      lastError = err;
      if (err instanceof ApiError && err.status >= 400 && err.status < 500) {
        throw err;
      }
      if (attempt === maxRetries) break;
      const delay = baseDelay * Math.pow(2, attempt);
      await new Promise((resolve) => setTimeout(resolve, delay));
    }
  }
  throw lastError;
}

export type ApplyDecisionCardInput = {
  chatMessageId: string;
  toolName: string;
  toolInput: Record<string, unknown>;
};

export async function applyDecisionCard(input: ApplyDecisionCardInput): Promise<unknown> {
  return apiFetch<unknown>('/chat/apply', {
    method: 'POST',
    body: {
      chatMessageId: input.chatMessageId,
      toolName: input.toolName,
      toolInput: input.toolInput,
    },
  });
}
