/**
 * PhotoAttachStrip — horizontal row of thumbnails above the chat input.
 *
 * Each thumbnail represents one staged photo. The supervisor can remove an
 * attachment by tapping the small "x" badge on its top-right corner.
 *
 * Three lifecycle states per thumbnail:
 *
 *   - 'pending'  — picked locally, not yet uploaded. Renders a translucent
 *                  overlay + small spinning dot.
 *   - 'uploaded' — S3 PUT succeeded; the GET URL is on the entry. Ready
 *                  to be included in the next chat send.
 *   - 'failed'   — upload failed. Renders a red border + "tap to retry"
 *                  hint. Retry handler lifts to parent.
 *
 * Max 4 attachments per message per the Wave 3 backend cap. The parent
 * disables the photo button when `attachments.length >= 4`.
 *
 * Image rendering: uses React Native's built-in `Image`. On web this maps
 * to `<img>` which already has browser-level caching. On native, RN's
 * default cache is adequate for previews of 4 small thumbnails — we do not
 * pull in `expo-image` for this slice because it is not yet in deps and
 * the marginal paint benefit on a 64×64 thumbnail is below the JND.
 *
 * @derives(supervisor-drawer-and-decisions-redesign.md §C — chat photo attach)
 * @derives(ADR-0003) @derives(master-plan §G) — supervisor surface
 */

import { View, Text, Pressable, StyleSheet, Image } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { tokens } from '@axhy/ui-tokens';

/**
 * One staged photo, held in chat-surface state until the send fires (or
 * the supervisor removes it).
 */
export type AttachmentDraft = {
  /** Locally-unique id, generated by the chat surface. */
  readonly id: string;
  /** Preview source — object URL on web, file URI on native. */
  readonly previewUri: string;
  readonly status: 'pending' | 'uploaded' | 'failed';
  /**
   * Set once `status === 'uploaded'`. This is the signed GET URL that
   * goes onto the chat send body's `attachments[]`.
   */
  readonly uploadedUrl?: string;
  /** Reason the upload failed, surfaced as a tooltip on hover (web). */
  readonly errorMessage?: string;
};

export type PhotoAttachStripProps = {
  readonly attachments: ReadonlyArray<AttachmentDraft>;
  readonly onRemove: (id: string) => void;
  readonly onRetry: (id: string) => void;
};

export function PhotoAttachStrip(props: PhotoAttachStripProps): React.JSX.Element | null {
  if (props.attachments.length === 0) return null;

  return (
    <View style={s.row} accessibilityLabel={`${props.attachments.length} photos attached`}>
      {props.attachments.map((a) => (
        <View key={a.id} style={s.thumbWrap}>
          <Pressable
            onPress={() => (a.status === 'failed' ? props.onRetry(a.id) : undefined)}
            accessibilityRole={a.status === 'failed' ? 'button' : 'image'}
            accessibilityLabel={
              a.status === 'failed'
                ? `Upload failed${a.errorMessage ? `: ${a.errorMessage}` : ''}. Tap to retry.`
                : a.status === 'pending'
                  ? 'Uploading photo'
                  : 'Photo attached'
            }
            style={[s.thumbInner, a.status === 'failed' && s.thumbFailed]}
          >
            <Image source={{ uri: a.previewUri }} style={s.thumbImg} resizeMode="cover" />
            {a.status === 'pending' ? (
              <View style={s.pendingOverlay}>
                <Text style={s.pendingDot}>…</Text>
              </View>
            ) : null}
            {a.status === 'failed' ? (
              <View style={s.failedOverlay}>
                <Feather name="refresh-cw" size={14} color={tokens.color.surface.card} />
              </View>
            ) : null}
          </Pressable>
          <Pressable
            onPress={() => props.onRemove(a.id)}
            accessibilityRole="button"
            accessibilityLabel="Remove photo"
            style={s.removeBadge}
            hitSlop={8}
          >
            <Feather name="x" size={12} color={tokens.color.surface.card} />
          </Pressable>
        </View>
      ))}
    </View>
  );
}

const THUMB_SIZE = 56;

const s = StyleSheet.create({
  row: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: tokens.space[2],
    paddingHorizontal: tokens.space[3],
    paddingVertical: tokens.space[2],
    backgroundColor: tokens.color.surface.paper,
    borderTopWidth: 1,
    borderColor: tokens.color.surface.cardEdge,
  },
  thumbWrap: {
    position: 'relative',
    width: THUMB_SIZE,
    height: THUMB_SIZE,
  },
  thumbInner: {
    width: THUMB_SIZE,
    height: THUMB_SIZE,
    borderRadius: tokens.radius.r2,
    overflow: 'hidden',
    backgroundColor: tokens.color.surface.paper2,
    borderWidth: 1,
    borderColor: tokens.color.surface.cardEdge,
  },
  thumbFailed: {
    borderColor: tokens.color.semantic.bad,
    borderWidth: 2,
  },
  thumbImg: {
    width: '100%',
    height: '100%',
  },
  pendingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingDot: {
    color: tokens.color.surface.card,
    fontSize: 18,
    fontWeight: '700',
  },
  failedOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: tokens.color.ink.primary,
    alignItems: 'center',
    justifyContent: 'center',
    // iOS shadow
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
  },
});
